MODEL:
  DEVICE: 'cpu'
  NAME: 'hacnn'
  PRETRAIN_PATH: ''
  USE_BNNECK: True
  WIDTH_MULT: 2. 
  IMAGENET: False
  PARALLEL: False 
  BEFORE_GAP: False
  NECK: False
  PCB_NECK: False
  MID_PLANES: 256
  LEARN_REGION: True 

DATASET:
  NAME: 'market1501'

DATA:
  IMAGE_SIZE: [160, 64]
  HF_PROB: 0.5
  RE_PROB: 0.5
  MEAN: [0.485, 0.456, 0.406]
  STD: [0.229, 0.224, 0.225]
  PADDING: 10

DATALOADER:
  NUM_WORKERS: 8
  SAMPLER: 'triplet'
  NUM_INSTANCE: 4

SOLVER:
  MAX_EPOCHS: 300
  END_EPOCH: 300
  IMGS_PER_BATCH: 64

  BASE_LR: 0.01
  # BASE_LR: 0.025
  MILESTONES: [150, 225]
  LR_LIST: [1.e-2, 1.e-3, 1.e-4]
  LR_DECAY_PERIOD: 40
  LR_DECAY_FACTOR: 0.1
  # LR_SCHEDULER_NAME: "WarmupCosAnnLR"
  LR_SCHEDULER_NAME: "WarmupMultiStepLR"
  LR_MIN: 0.001

  WARMUP_ITERS: 0
  WARMUP_FACTOR: 0.1
  GAMA: 0.1

  OPTIMIZER_NAME: "SGD"
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.005

  LOSS_NAME: "softmax_triplet"
  TRI_MARGIN: 0.3

TEST:
  IMGS_PER_BATCH: 128
  FEAT_NORM: 'yes'
  BEST_CKPT: "best_ckpt.pth"

OUTPUT:
  ROOT_DIR: "/home/share/solicucu/data/ReID/MobileNetReID/hacnn/"
  CKPT_DIR: "checkpoints/hacnn_3step_sgd_e300/"
  LOG_PERIOD: 10
  LOG_NAME: 'log_hacnn_kaiming_3step_sgd_e300.txt'
  CHECKPOINT_PERIOD: 20
  EVAL_PERIOD: 20
