MODEL:
  DEVICE: 'cpu'
  NAME: 'ssnet'
  PRETRAIN_PATH: '/home/share/solicucu/data/ReID/MobileNetReID/imagenet/checkpoints/ssnetv4_fa_kc_wd0005/'
  # PRETRAIN_PATH: '/home/share/solicucu/data/ReID/MobileNetReID/imagenet/checkpoints/mobilenetv2x2_kc/'
  USE_BNNECK: True
  WIDTH_MULT: 2. 
  IMAGENET: False
  PARALLEL: True
  BEFORE_GAP: False 
  NECK: False
  PCB_NECK: False
  MID_PLANES: 256

TRICKS:
  LABEL_SMOOTH: False
  LAST_STRIDE: 2

DATASET:
  NAME: 'imagenet'

DATA:
  IMAGE_SIZE: [224,224]
  HF_PROB: 0.5
  RE_PROB: 0.5
  MEAN: [0.485, 0.456, 0.406]
  STD: [0.229, 0.224, 0.225]
  PADDING: 10

DATALOADER:
  NUM_WORKERS: 4
  SAMPLER: 'triplet'
  NUM_INSTANCE: 4

SOLVER:
  MAX_EPOCHS: 60
  END_EPOCH: 60
  IMGS_PER_BATCH: 64

  BASE_LR: 0.025
  # BASE_LR: 0.05
  LR_LIST: [1.5e-2, 1.5e-3, 1.5e-4]
  MILESTONES: [150, 225]
  # BASE_LR: 0.025
  LR_DECAY_PERIOD: 40
  LR_DECAY_FACTOR: 0.1
  LR_SCHEDULER_NAME: "WarmupCosAnnLR"
  # LR_SCHEDULER_NAME: "WarmupMultiStepLR"
  LR_MIN: 0.00001

  WARMUP_ITERS: 0
  WARMUP_FACTOR: 1.0
  GAMA: 0.1

  OPTIMIZER_NAME: "SGD"
  MOMENTUM: 0.9
  # WEIGHT_DECAY: 0.00004
  WEIGHT_DECAY: 0.0005

  LOSS_NAME: "softmax_triplet"
  TRI_MARGIN: 0.3

TEST:
  IMGS_PER_BATCH: 128
  FEAT_NORM: 'yes'
  BEST_CKPT: "best_ckpt.pth"

OUTPUT:
  ROOT_DIR: "/home/share/solicucu/data/ReID/MobileNetReID/imagenet/"
  CKPT_DIR: "checkpoints/ssnetv4_fa_kc_wd0005/"
  LOG_PERIOD: 100
  LOG_NAME: 'log_imagenet_ssnetv4_fa_kc_wd0005_3.txt'
  CHECKPOINT_PERIOD: 5
  EVAL_PERIOD: 10

DARTS:
  IN_PLANES: 60
  LAYERS: [3, 4, 6, 3]
  GENOTYPE: 'v4_best_genotype.json'
  CKPT_NAME: 'best_ckpt_fit.pth'
  PRETRAINED: False
  GRAD_CLIP: 5.
  MULTIPLIER: 2
  USE_ATTENTION: True
